swagger: '2.0'
info:
  version: 1.0.0
  title: Nature API
  description: Read/Write Nature Remo
host: api.nature.global
basePath: /
schemes:
  - https
securityDefinitions:
  oauth2:
    type: oauth2
    scopes:
      basic.read: Read only access to user's profile (excluding email), Remos, appliances, signals.
      basic: Read + write access to user's profile (excluding email), Remos, appliances, signals.
      sendir: Send infrared signals through Remo.
      detectappliance: Detect air conditioner model from infrared signals.
    flow: accessCode
    authorizationUrl: https://api.nature.global/oauth2/auth
    tokenUrl: https://api.nature.global/oauth2/token
paths:
  /1/users/me:
    get:
      description: Fetch the authenticated user's information.
      security:
       - oauth2:
         - basic.read
    post:
      description: Update authenticated user's information.
      security:
       - oauth2:
         - basic
  /1/devices:
    get:
      description: Fetch the list of Remo devices the user has access to.
      security:
       - oauth2:
         - basic.read
  /1/detectappliance:
    post:
      description: Find the air conditioner best matching the provided infrared signal.
      security:
       - oauth2:
         - detectappliance
  /1/appliances:
    get:
      description: Fetch the list of appliances.
      security:
       - oauth2:
         - basic.read
    post:
      description: Create a new appliance.
      security:
       - oauth2:
         - basic
  /1/appliance_orders:
    post:
      description: Reorder appliances.
      security:
       - oauth2:
         - basic
  /1/appliances/{appliance}/delete:
    post:
      description: Delete appliance.
      security:
       - oauth2:
         - basic
  /1/appliances/{appliance}:
    post:
      description: Update appliance.
      security:
       - oauth2:
         - basic
  /1/appliances/{appliance}/aircon_settings:
    post:
      description: Update air conditioner settings.
      security:
       - oauth2:
         - sendir
  /1/appliances/{appliance}/tv:
    post:
      description: Send tv infrared signal.
      security:
       - oauth2:
         - sendir
  /1/appliances/{appliance}/light:
    post:
      description: Send light infrared signal.
      security:
       - oauth2:
         - sendir
  /1/appliances/{appliance}/signals:
    get:
      description: Fetch signals registered under this appliance.
      security:
       - oauth2:
         - basic.read
    post:
      description: Create a signal under this appliance.
      security:
       - oauth2:
         - basic
  /1/appliances/{appliance}/signal_orders:
    post:
      description: Reorder signals under this appliance.
      security:
       - oauth2:
         - basic
  /1/signals/{signal}:
    post:
      description: Update infrared signal.
      security:
       - oauth2:
         - basic
  /1/signals/{signal}/delete:
    post:
      description: Delete an infrared signal.
      security:
       - oauth2:
         - basic
  /1/signals/{signal}/send:
    post:
      description: Send infrared signal.
      security:
       - oauth2:
         - sendir
  /1/devices/{device}:
    post:
      description: Update Remo
      security:
       - oauth2:
         - basic
  /1/devices/{device}/delete:
    post:
      description: Delete Remo.
      security:
       - oauth2:
         - basic
  /1/devices/{device}/temperature_offset:
    post:
      description: Update temperature offset.
      security:
       - oauth2:
         - basic
  /1/devices/{device}/humidity_offset:
    post:
      description: Update humidity offset.
      security:
       - oauth2:
         - basic